# Load the base image
FROM fedora:41

# Numerics research group
LABEL maintainer="numerics@iag.uni-stuttgart.de"

# Setup required packages
RUN dnf makecache && \
    dnf update -y && \
    dnf install -y git python3 uv && \
    dnf clean all

# Set architecture argument
ARG ARCH

# Setup uv
ENV UV_LINK_MODE=copy

# Setup Ruff
RUN dnf install -y ruff

# Setup Fortitude
RUN dnf install -y cargo
RUN uv tool install git+https://github.com/PlasmaFAIR/fortitude
ENV PATH="/root/.local/bin:$PATH"
