FROM sphinxdoc/sphinx-latexpdf:latest

ARG NB_USER=gitlab-runner
ARG NB_UID=987
ARG NB_GID=987

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    ssh rsync
RUN mkdir /mymount

RUN groupadd --gid ${NB_GID} ${NB_USER} && \
    useradd  --gid ${NB_GID} --uid ${NB_UID} -m -s /bin/bash ${NB_USER}

USER ${NB_USER}
RUN mkdir /home/${NB_USER}/.ssh
#ENV SSH_AUTH_SOCK=/ssh-agent
